# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
# Sonata Admin
    admin.post:
        class: AppBundle\Admin\PostAdmin
        arguments: [ ~, AppBundle\Entity\Post, AppBundle:Admin\PostAdmin, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Articles", group: "Blog" }
    admin.tag:
        class: AppBundle\Admin\TagAdmin
        arguments: [ ~, AppBundle\Entity\Tag, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Etiquetes", group: "Blog" }
    admin.contactmessage:
        class: AppBundle\Admin\ContactMessageAdmin
        arguments: [ ~, AppBundle\Entity\ContactMessage, AppBundle:Admin\ContactMessageAdmin, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager", "@app.repositories_manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Missatge de Contacte", group: "Contactes" }
    admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [ ~, AppBundle\Entity\User, ~, "@fos_user.user_manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Usuari", group: "Usuarios" }
